<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TerritoryController extends Controller
{
    public function index()
    {
        $territories = [
            'binjai' => [
                'name' => 'BINJAI',
                'subtitle' => 'Pemkab Langkat, Pemkot Binjai',
                'map_image' => 'assets/img/binjai-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.116'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.116'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.116'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.116'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.116'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.116'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.116'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.116'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.116'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.116'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.116'],               
                ],
                'occ' => '60,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkab Langkat', 'Pemkot Binjai'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 10],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 8],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 88],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 12],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 31],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
            'kabanjahe' => [
                'name' => 'KABANJAHE',
                'subtitle' => 'Pemkab Dairi, Pemkab Karo, Pemkab Pakpak Bharat',
                'map_image' => 'assets/img/kabanjahe-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.115'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.115'],               
                ],
                'occ' => '60,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkab Dairi', 'Pemkot Karo','Pemkab Pakpak Bharat'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 9],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 8],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 66],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 52],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 43],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
            'siantar' => [
                'name' => 'SIANTAR',
                'subtitle' => 'Pemkab Simalungun, Pemkot Pematang Siantar',
                'map_image' => 'assets/img/siantar-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.119'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.110'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.223'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.115'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.115'],               
                ],
                'occ' => '60,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkab Simalungun', 'Pemkot Pematang Siantar'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 9],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 10],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 45],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 52],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 63],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
            'toba' => [
                'name' => 'TOBA',
                'subtitle' => 'Pemkab Humbang Hasundutan, Pemkab Samosir, Pemkab Tapanuli Utara, Pemkab Toba Samosir',
                'map_image' => 'assets/img/toba-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.200'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.110'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.223'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.115'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.115'],               
                ],
                'occ' => '69,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkab Humbang Hasundutan', 'Pemkab Samosir', 'Pemkab Tapanuli Utara', 'Pemkab Toba Samosir'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 20],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 10],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 45],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 52],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 63],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
            'sibolga' => [
                'name' => 'SIBOLGA',
                'subtitle' => 'Pemkab Nias, Pemkab Nias Barat, Pemkab Nias Selatan, Pemkab Nias Utara, Pemkab Tapanuli Tengah, Pemkot Gunung Sitoli, Pemkot Sibolga',
                'map_image' => 'assets/img/sibolga-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.200'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.110'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.223'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.115'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.115'],               
                ],
                'occ' => '69,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkab Nias', 'Pemkab Nias Barat', 'Pemkab Nias Selatan', 'Pemkab Nias Utara', 'Pemkab Tapanuli Tengah', 'Pemkot Gunung Sitoli', 'Pemkot Sibolga'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 20],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 10],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 45],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 52],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 63],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
            'inner-sumut' => [
                'name' => 'INNER SUMUT',
                'subtitle' => 'Pemkot Medan, Pemprov Sumut, Polda Sumatera Utara',
                'map_image' => 'assets/img/inner-sumut-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.200'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.110'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.223'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.115'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.115'],               
                ],
                'occ' => '69,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkot Medan', 'Pemprov Sumut', 'Polda Sumatera Utara'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 20],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 10],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 45],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 52],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 63],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
            'lubuk-pakam' => [
                'name' => 'LUBUK PAKAM',
                'subtitle' => 'Pemkab Deli Serdang, Pemkab Serdang Bedagai, Pemkot Tebing Tinggi',
                'map_image' => 'assets/img/lubuk-pakam-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.250'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.310'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.435'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.115'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.115'],               
                ],
                'occ' => '69,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkab Deli Serdang', 'Pemkab Serdang Bedagai', 'Pemkot Tebing Tinggi'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 25],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 60],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 45],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 52],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 63],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
            'kisaran' => [
                'name' => 'KISARAN',
                'subtitle' => 'Pemkab Asahan, Pemkab Batubara, Pemkot Tanjung Balai',
                'map_image' => 'assets/img/kisaran-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.900'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.810'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.735'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.115'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.115'],               
                ],
                'occ' => '69,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkab Asahan', 'Pemkab Batubara', 'Pemkot Tanjung Balai'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 65],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 60],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 45],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 52],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 63],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
            'rantau-prapat' => [
                'name' => 'RANTAU PRAPAT',
                'subtitle' => 'Pemkab Labuhan Batu, Pemkab Labuhan Batu Selatan, Pemkab Labuhan Batu Utara',
                'map_image' => 'assets/img/rantau-prapat-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.890'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.810'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.735'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.256'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.300'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.115'],               
                ],
                'occ' => '70,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkab Labuhan Batu', 'Pemkab Labuhan Batu Selatan', 'Pemkab Labuhan Batu Utara'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 90],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 75],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 80],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 52],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 63],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
            'padang-sidempuan' => [
                'name' => 'PADANG SIDEMPUAN',
                'subtitle' => 'Pemkab Mandailing Natal, Pemkab Padang Lawas, Pemkab Padang Lawas Utara, Pemkab Tapanuli Selatan, Pemkab Padangsidempuan',
                'map_image' => 'assets/img/padang-sidempuan-map.png',
                'opportunities' => [
                    ['icon' => 'assets/img/opportunity-ruko.png', 'label' => 'RUKO', 'count' => '16.890'],
                    ['icon' => 'assets/img/opportunity-sekolah.png', 'label' => 'SEKOLAH', 'count' => '16.810'],
                    ['icon' => 'assets/img/opportunity-hotel.png', 'label' => 'HOTEL', 'count' => '16.735'],
                    ['icon' => 'assets/img/opportunity-health.png', 'label' => 'HEALTH', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-manufacture.png', 'label' => 'MANUFACTURE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-agrikultur.png', 'label' => 'AGRIKULTUR', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-media.png', 'label' => 'MEDIA', 'count' => '16.256'],
                    ['icon' => 'assets/img/opportunity-ekspedisi.png', 'label' => 'EKSPEDISI', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-multifinance.png', 'label' => 'MULTIFINANCE', 'count' => '16.115'],
                    ['icon' => 'assets/img/opportunity-property.png', 'label' => 'PROPERTY', 'count' => '16.300'], 
                    ['icon' => 'assets/img/opportunity-energy.png', 'label' => 'ENERGY', 'count' => '16.115'],               
                ],
                'occ' => '70,78%',
                'idle_port' => '1000',
                'opp_dgs' => ['Pemkab Mandailing Natal', 'Pemkab Padang Lawas', 'Pemkab Padang Lawas Utara', 'Pemkab Tapanuli Selatan', 'Pemkab Padangsidempuan'],
                'resources' => [
                    ['jabatan' => 'Account Manager', 'jumlah' => 90],
                    ['jabatan' => 'Mitra Agensi', 'jumlah' => 75],
                    ['jabatan' => 'Sales Assistant', 'jumlah' => 7],
                    ['jabatan' => 'Account Representative', 'jumlah' => 80],
                    ['jabatan' => 'Mitra PM', 'jumlah' => 52],
                    ['jabatan' => 'Head Of Telkom Daerah', 'jumlah' => 63],
                    ['jabatan' => 'Officer', 'jumlah' => '-'],
                ],
            ],
        ];

        return view('territory', compact('territories'));
    }
}
